version: "3"

services:
  chrome:
    image: selenium/standalone-chrome:4.0.0-beta-3-prerelease-20210402
    container_name: chrome
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 4444:4444
      - 5900:5900

  pytest:
    build: ./tests
    container_name: pytest
    volumes:
      - ./tests/src:/tests/src
    tty: true